# Generated by Django 3.2 on 2022-02-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=150)),
                ('amount_due', models.CharField(blank=True, max_length=150)),
                ('amount_paid', models.CharField(blank=True, max_length=150)),
                ('payment_date', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(blank=True, max_length=150)),
                ('depositor', models.CharField(blank=True, max_length=150)),
                ('balance_due', models.CharField(blank=True, max_length=150)),
                ('payment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.feespayments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
