# Generated by Django 3.2 on 2022-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('bank_deposit', 'cash'), ('cheque', 'cheque'), ('pos', 'pos')], max_length=50),
        ),
    ]
