# Generated by Django 3.2 on 2022-02-21 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20220221_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('bank_deposit', 'bank_deposit'), ('cheque', 'cheque'), ('pos', 'pos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
