# Generated by Django 3.2 on 2022-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('Select', 'Select'), ('Lagos', 'Lagos'), ('Ogun', 'Ogun')], default='Select', max_length=10),
        ),
    ]
