# Generated by Django 3.2 on 2022-09-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('last_class', models.CharField(max_length=150)),
                ('new_class', models.CharField(max_length=150)),
                ('application_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_admitted', models.DateField()),
                ('parent_name', models.CharField(blank=True, max_length=150)),
                ('parent_address', models.TextField(blank=True, max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('relationship', models.CharField(blank=True, max_length=30)),
                ('class_on_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, max_length=20)),
                ('student_type', models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='day_student', max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_admitted', models.DateField(null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150)),
                ('parent_address', models.TextField(blank=True, max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_email', models.CharField(blank=True, max_length=15, null=True)),
                ('relationship', models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('other', 'other')], default='mother', max_length=15)),
                ('class_on_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentdetails', to='curriculum.standard', verbose_name='class_on_admission')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile')),
                ('current_class', models.ForeignKey(default='jss1', on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mystudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('academic', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
