# Generated by Django 3.2 on 2022-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='student_status',
            field=models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='active_student', max_length=15),
        ),
    ]
