# Generated by Django 3.2 on 2022-02-21 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_on_admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_admitted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_address',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
