# Generated by Django 3.2 on 2022-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_code',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
