# Generated by Django 3.2 on 2022-02-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220221_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='relationship',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
