# Generated by Django 3.2 on 2022-02-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220221_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_admitted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
