# Generated by Django 3.2 on 2022-02-22 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
        ('students', '0004_auto_20220221_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
