# Generated by Django 3.2 on 2022-02-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0005_auto_20220222_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='current_class',
            field=models.ForeignKey(default='jss1', on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
    ]
