# Generated by Django 3.2 on 2022-03-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentacademicinfo_current_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentacademicinfo',
            old_name='user',
            new_name='student_user',
        ),
    ]
