# Generated by Django 3.2 on 2022-03-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_user_studentacademicinfo_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentacademicinfo',
            old_name='student_user',
            new_name='user',
        ),
    ]
