# Generated by Django 3.2 on 2022-03-16 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0005_auto_20220222_2221'),
        ('curriculum', '0001_initial'),
        ('students', '0010_auto_20220316_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAcademicInfo',
            new_name='StudentDetails',
        ),
    ]
