# Generated by Django 3.2 on 2022-03-22 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_auto_20220318_0029'),
        ('curriculum', '0001_initial'),
        ('students', '0011_rename_studentacademicinfo_studentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
