# Generated by Django 3.2 on 2022-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_studentdetails_studentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='class_on_admission',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='parent_email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='relationship',
            field=models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('other', 'other')], default='mother', max_length=15),
        ),
    ]
