# Generated by Django 3.2 on 2022-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid',
            field=models.CharField(max_length=150),
        ),
    ]
