# Generated by Django 3.2 on 2022-09-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('select', 'select')], default='select', max_length=15)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=150)),
                ('date_employed', models.DateField(null=True)),
                ('cat_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employed', models.DateField()),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('year', models.DateField()),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('select', 'select')], default='select', max_length=15)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=150)),
                ('guarantor_email', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=150)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('staff_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
