# Generated by Django 3.2 on 2022-02-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
    ]
