# Generated by Django 3.2 on 2022-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20220220_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='marital_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
