# Generated by Django 3.2 on 2022-02-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20220220_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='middle_name',
        ),
    ]
