# Generated by Django 3.2 on 2022-02-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20220220_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffacademicinfo',
            name='date_employed',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='marital_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='next_of_kin_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='staffacademicinfo',
            name='staff_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffcategory'),
        ),
    ]
