# Generated by Django 3.2 on 2022-03-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffacademicinfo_date_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffacademicinfo',
            name='date_employed',
            field=models.DateField(null=True, verbose_name='date employed'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_employed',
            field=models.DateField(null=True, verbose_name='date employed'),
        ),
    ]
