# Generated by Django 3.2 on 2022-03-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20220318_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffacademicinfo',
            name='date_employed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_employed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
