# Generated by Django 3.2 on 2022-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20220318_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffacademicinfo',
            name='date_employed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_employed',
            field=models.DateField(null=True),
        ),
    ]
