# Generated by Django 3.2 on 2022-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='post_pic1.jpg', upload_to='post_pics'),
        ),
    ]
