# Generated by Django 3.2 on 2022-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=models.CharField(max_length=250),
        ),
    ]
