# Generated by Django 3.2 on 2022-04-17 12:56

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_lesson_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
