# Generated by Django 3.2 on 2022-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to='save_lesson_files', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, upload_to='save_lesson_files', verbose_name='Presentation'),
        ),
    ]
