# Generated by Django 3.2 on 2022-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
