# Generated by Django 3.2 on 2022-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=11, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=11, null=True)),
                ('attendance_date', models.DateField(null=True)),
            ],
        ),
    ]
