# Generated by Django 3.2 on 2022-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_name',
            new_name='select_class',
        ),
        migrations.AddField(
            model_name='attendance',
            name='select_student',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
